import { ThemeProvider } from "@/components/theme-provider"
import { Inter } from "next/font/google"
import "./globals.css"
import NavigationSidebar from "@/components/navigation/navigation-sidebar"
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NavigationSidebar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
